// Borland C++ Builder
// Copyright (c) 1995, 2002 by Borland Software Corporation
// All rights reserved

// (DO NOT EDIT: machine generated header) 'TeeConst.pas' rev: 6.00

#ifndef TeeConstHPP
#define TeeConstHPP

#pragma delphiheader begin
#pragma option push -w-
#pragma option push -Vx
#include <Classes.hpp>	// Pascal unit
#include <SysInit.hpp>	// Pascal unit
#include <System.hpp>	// Pascal unit

//-- user supplied -----------------------------------------------------------

namespace Teeconst
{
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------
extern PACKAGE AnsiString TeeMsg_TeeExtension;
#define TeeChartVersion "8"
#define TeeVCLMinorVersion ".06"
#define TeeVCLBuildVersion "60902"
#define TeeMsg_Version "TeeChart Pro v8.06.60902"
#define TeeMsg_EditorKey "SOFTWARE\\Steema Software\\TeeChart Pro\\Editor"
#define TeeMsg_GalleryChartName "TeeGalleryChart"
#define TeeMsg_TeeChartIDWizard "TeeChart.TeeChartWizard"
#define TeeMsg_TeeChartSL "Steema Software SL"
#define TeeMsg_TeeChartPalette "TeeChart"
#define TeeMsg_DefaultEngFontName "Arial"
#define TeeMsg_DefaultDemoTee "http://www.steema.com/demo.tee"
#define TeeMsg_HHNNSS "[hh:nn:ss]"
extern PACKAGE AnsiString TeeMsg_Copyright;
extern PACKAGE AnsiString TeeMsg_Test;
extern PACKAGE AnsiString TeeMsg_LegendFirstValue;
extern PACKAGE AnsiString TeeMsg_LegendColorWidth;
extern PACKAGE AnsiString TeeMsg_SeriesSetDataSource;
extern PACKAGE AnsiString TeeMsg_SeriesInvDataSource;
extern PACKAGE AnsiString TeeMsg_FillSample;
extern PACKAGE AnsiString TeeMsg_AxisLogDateTime;
extern PACKAGE AnsiString TeeMsg_AxisLogNotPositive;
extern PACKAGE AnsiString TeeMsg_AxisLabelSep;
extern PACKAGE AnsiString TeeMsg_AxisIncrementNeg;
extern PACKAGE AnsiString TeeMsg_AxisMinMax;
extern PACKAGE AnsiString TeeMsg_AxisMaxMin;
extern PACKAGE AnsiString TeeMsg_AxisLogBase;
extern PACKAGE AnsiString TeeMsg_MaxPointsPerPage;
extern PACKAGE AnsiString TeeMsg_3dPercent;
extern PACKAGE AnsiString TeeMsg_CircularSeries;
extern PACKAGE AnsiString TeeMsg_WarningHiColor;
extern PACKAGE AnsiString TeeMsg_DefaultPercentOf;
extern PACKAGE AnsiString TeeMsg_DefaultPercentOf2;
extern PACKAGE AnsiString TeeMsg_DefPercentFormat;
extern PACKAGE AnsiString TeeMsg_DefValueFormat;
extern PACKAGE AnsiString TeeMsg_DefLogValueFormat;
extern PACKAGE AnsiString TeeMsg_AxisTitle;
extern PACKAGE AnsiString TeeMsg_AxisLabels;
extern PACKAGE AnsiString TeeMsg_RefreshInterval;
extern PACKAGE AnsiString TeeMsg_SeriesParentNoSelf;
extern PACKAGE AnsiString TeeMsg_GalleryLine;
extern PACKAGE AnsiString TeeMsg_GalleryPoint;
extern PACKAGE AnsiString TeeMsg_GalleryArea;
extern PACKAGE AnsiString TeeMsg_GalleryBar;
extern PACKAGE AnsiString TeeMsg_GalleryHorizBar;
extern PACKAGE AnsiString TeeMsg_Stack;
extern PACKAGE AnsiString TeeMsg_GalleryPie;
extern PACKAGE AnsiString TeeMsg_GalleryCircled;
extern PACKAGE AnsiString TeeMsg_GalleryFastLine;
extern PACKAGE AnsiString TeeMsg_GalleryHorizLine;
extern PACKAGE AnsiString TeeMsg_PieSample1;
extern PACKAGE AnsiString TeeMsg_PieSample2;
extern PACKAGE AnsiString TeeMsg_PieSample3;
extern PACKAGE AnsiString TeeMsg_PieSample4;
extern PACKAGE AnsiString TeeMsg_PieSample5;
extern PACKAGE AnsiString TeeMsg_PieSample6;
extern PACKAGE AnsiString TeeMsg_PieSample7;
extern PACKAGE AnsiString TeeMsg_PieSample8;
extern PACKAGE AnsiString TeeMsg_GalleryLogoFont;
extern PACKAGE AnsiString TeeMsg_Editing;
extern PACKAGE AnsiString TeeMsg_GalleryStandard;
extern PACKAGE AnsiString TeeMsg_GalleryExtended;
extern PACKAGE AnsiString TeeMsg_GalleryFunctions;
extern PACKAGE AnsiString TeeMsg_EditChart;
extern PACKAGE AnsiString TeeMsg_PrintPreview;
extern PACKAGE AnsiString TeeMsg_ExportChart;
extern PACKAGE AnsiString TeeMsg_CustomAxes;
extern PACKAGE AnsiString TeeMsg_InvalidEditorClass;
extern PACKAGE AnsiString TeeMsg_MissingEditorClass;
extern PACKAGE AnsiString TeeMsg_GalleryArrow;
extern PACKAGE AnsiString TeeMsg_ExpFinish;
extern PACKAGE AnsiString TeeMsg_ExpNext;
extern PACKAGE AnsiString TeeMsg_GalleryGantt;
extern PACKAGE AnsiString TeeMsg_GanttSample1;
extern PACKAGE AnsiString TeeMsg_GanttSample2;
extern PACKAGE AnsiString TeeMsg_GanttSample3;
extern PACKAGE AnsiString TeeMsg_GanttSample4;
extern PACKAGE AnsiString TeeMsg_GanttSample5;
extern PACKAGE AnsiString TeeMsg_GanttSample6;
extern PACKAGE AnsiString TeeMsg_GanttSample7;
extern PACKAGE AnsiString TeeMsg_GanttSample8;
extern PACKAGE AnsiString TeeMsg_GanttSample9;
extern PACKAGE AnsiString TeeMsg_GanttSample10;
extern PACKAGE AnsiString TeeMsg_ChangeSeriesTitle;
extern PACKAGE AnsiString TeeMsg_NewSeriesTitle;
extern PACKAGE AnsiString TeeMsg_DateTime;
extern PACKAGE AnsiString TeeMsg_TopAxis;
extern PACKAGE AnsiString TeeMsg_BottomAxis;
extern PACKAGE AnsiString TeeMsg_LeftAxis;
extern PACKAGE AnsiString TeeMsg_RightAxis;
extern PACKAGE AnsiString TeeMsg_SureToDelete;
extern PACKAGE AnsiString TeeMsg_DateTimeFormat;
extern PACKAGE AnsiString TeeMsg_Default;
extern PACKAGE AnsiString TeeMsg_ValuesFormat;
extern PACKAGE AnsiString TeeMsg_Maximum;
extern PACKAGE AnsiString TeeMsg_Minimum;
extern PACKAGE AnsiString TeeMsg_DesiredIncrement;
extern PACKAGE AnsiString TeeMsg_IncorrectMaxMinValue;
extern PACKAGE AnsiString TeeMsg_EnterDateTime;
extern PACKAGE AnsiString TeeMsg_SureToApply;
extern PACKAGE AnsiString TeeMsg_SelectedSeries;
extern PACKAGE AnsiString TeeMsg_RefreshData;
extern PACKAGE AnsiString TeeMsg_DefaultFontSize;
extern PACKAGE AnsiString TeeMsg_DefaultEditorSize;
extern PACKAGE AnsiString TeeMsg_DefaultEditorHeight;
extern PACKAGE AnsiString TeeMsg_FunctionAdd;
extern PACKAGE AnsiString TeeMsg_FunctionSubtract;
extern PACKAGE AnsiString TeeMsg_FunctionMultiply;
extern PACKAGE AnsiString TeeMsg_FunctionDivide;
extern PACKAGE AnsiString TeeMsg_FunctionHigh;
extern PACKAGE AnsiString TeeMsg_FunctionLow;
extern PACKAGE AnsiString TeeMsg_FunctionAverage;
extern PACKAGE AnsiString TeeMsg_GalleryShape;
extern PACKAGE AnsiString TeeMsg_GalleryBubble;
extern PACKAGE AnsiString TeeMsg_FunctionNone;
extern PACKAGE AnsiString TeeMsg_None;
extern PACKAGE AnsiString TeeMsg_PrivateDeclarations;
extern PACKAGE AnsiString TeeMsg_PublicDeclarations;
extern PACKAGE AnsiString TeeMsg_DefaultFontName;
extern PACKAGE AnsiString TeeMsg_CheckPointerSize;
extern PACKAGE AnsiString TeeMsg_About;
extern PACKAGE AnsiString tcAdditional;
extern PACKAGE AnsiString tcDControls;
extern PACKAGE AnsiString tcQReport;
extern PACKAGE AnsiString TeeMsg_DataSet;
extern PACKAGE AnsiString TeeMsg_AskDataSet;
extern PACKAGE AnsiString TeeMsg_SingleRecord;
extern PACKAGE AnsiString TeeMsg_AskDataSource;
extern PACKAGE AnsiString TeeMsg_Summary;
extern PACKAGE AnsiString TeeMsg_FunctionPeriod;
extern PACKAGE AnsiString TeeMsg_WizardTab;
extern PACKAGE AnsiString TeeMsg_TeeChartWizard;
extern PACKAGE AnsiString TeeMsg_ClearImage;
extern PACKAGE AnsiString TeeMsg_BrowseImage;
extern PACKAGE AnsiString TeeMsg_WizardSureToClose;
extern PACKAGE AnsiString TeeMsg_FieldNotFound;
extern PACKAGE AnsiString TeeMsg_DepthAxis;
extern PACKAGE AnsiString TeeMsg_PieOther;
extern PACKAGE AnsiString TeeMsg_ShapeGallery1;
extern PACKAGE AnsiString TeeMsg_ShapeGallery2;
extern PACKAGE AnsiString TeeMsg_ValuesX;
extern PACKAGE AnsiString TeeMsg_ValuesY;
extern PACKAGE AnsiString TeeMsg_ValuesPie;
extern PACKAGE AnsiString TeeMsg_ValuesBar;
extern PACKAGE AnsiString TeeMsg_ValuesAngle;
extern PACKAGE AnsiString TeeMsg_ValuesGanttStart;
extern PACKAGE AnsiString TeeMsg_ValuesGanttEnd;
extern PACKAGE AnsiString TeeMsg_ValuesGanttNextTask;
extern PACKAGE AnsiString TeeMsg_ValuesBubbleRadius;
extern PACKAGE AnsiString TeeMsg_ValuesArrowEndX;
extern PACKAGE AnsiString TeeMsg_ValuesArrowEndY;
extern PACKAGE AnsiString TeeMsg_Legend;
extern PACKAGE AnsiString TeeMsg_Title;
extern PACKAGE AnsiString TeeMsg_Foot;
extern PACKAGE AnsiString TeeMsg_Period;
extern PACKAGE AnsiString TeeMsg_PeriodRange;
extern PACKAGE AnsiString TeeMsg_CalcPeriod;
extern PACKAGE AnsiString TeeMsg_SmallDotsPen;
extern PACKAGE AnsiString TeeMsg_InvalidTeeFile;
extern PACKAGE AnsiString TeeMsg_WrongTeeFileFormat;
extern PACKAGE AnsiString TeeMsg_EmptyTeeFile;
extern PACKAGE AnsiString TeeMsg_ChartAxesCategoryName;
extern PACKAGE AnsiString TeeMsg_ChartAxesCategoryDesc;
extern PACKAGE AnsiString TeeMsg_ChartWallsCategoryName;
extern PACKAGE AnsiString TeeMsg_ChartWallsCategoryDesc;
extern PACKAGE AnsiString TeeMsg_ChartTitlesCategoryName;
extern PACKAGE AnsiString TeeMsg_ChartTitlesCategoryDesc;
extern PACKAGE AnsiString TeeMsg_Chart3DCategoryName;
extern PACKAGE AnsiString TeeMsg_Chart3DCategoryDesc;
extern PACKAGE AnsiString TeeMsg_CustomAxesEditor;
extern PACKAGE AnsiString TeeMsg_Series;
extern PACKAGE AnsiString TeeMsg_SeriesList;
extern PACKAGE AnsiString TeeMsg_PageOfPages;
extern PACKAGE AnsiString TeeMsg_FileSize;
extern PACKAGE AnsiString TeeMsg_First;
extern PACKAGE AnsiString TeeMsg_Prior;
extern PACKAGE AnsiString TeeMsg_Next;
extern PACKAGE AnsiString TeeMsg_Last;
extern PACKAGE AnsiString TeeMsg_Insert;
extern PACKAGE AnsiString TeeMsg_Delete;
extern PACKAGE AnsiString TeeMsg_Edit;
extern PACKAGE AnsiString TeeMsg_Post;
extern PACKAGE AnsiString TeeMsg_Cancel;
extern PACKAGE AnsiString TeeMsg_All;
extern PACKAGE AnsiString TeeMsg_Index;
extern PACKAGE AnsiString TeeMsg_Text;
extern PACKAGE AnsiString TeeMsg_AsBMP;
extern PACKAGE AnsiString TeeMsg_BMPFilter;
extern PACKAGE AnsiString TeeMsg_AsEMF;
extern PACKAGE AnsiString TeeMsg_EMFFilter;
extern PACKAGE AnsiString TeeMsg_ExportPanelNotSet;
extern PACKAGE AnsiString TeeMsg_Normal;
extern PACKAGE AnsiString TeeMsg_NoBorder;
extern PACKAGE AnsiString TeeMsg_Dotted;
extern PACKAGE AnsiString TeeMsg_Colors;
extern PACKAGE AnsiString TeeMsg_Filled;
extern PACKAGE AnsiString TeeMsg_Marks;
extern PACKAGE AnsiString TeeMsg_Stairs;
extern PACKAGE AnsiString TeeMsg_Points;
extern PACKAGE AnsiString TeeMsg_Height;
extern PACKAGE AnsiString TeeMsg_Hollow;
extern PACKAGE AnsiString TeeMsg_Point2D;
extern PACKAGE AnsiString TeeMsg_Triangle;
extern PACKAGE AnsiString TeeMsg_Star;
extern PACKAGE AnsiString TeeMsg_Circle;
extern PACKAGE AnsiString TeeMsg_DownTri;
extern PACKAGE AnsiString TeeMsg_Cross;
extern PACKAGE AnsiString TeeMsg_Diamond;
extern PACKAGE AnsiString TeeMsg_NoLines;
extern PACKAGE AnsiString TeeMsg_Stack100;
extern PACKAGE AnsiString TeeMsg_Pyramid;
extern PACKAGE AnsiString TeeMsg_Ellipse;
extern PACKAGE AnsiString TeeMsg_InvPyramid;
extern PACKAGE AnsiString TeeMsg_Sides;
extern PACKAGE AnsiString TeeMsg_SideAll;
extern PACKAGE AnsiString TeeMsg_Patterns;
extern PACKAGE AnsiString TeeMsg_Exploded;
extern PACKAGE AnsiString TeeMsg_Shadow;
extern PACKAGE AnsiString TeeMsg_SemiPie;
extern PACKAGE AnsiString TeeMsg_Rectangle;
extern PACKAGE AnsiString TeeMsg_VertLine;
extern PACKAGE AnsiString TeeMsg_HorizLine;
extern PACKAGE AnsiString TeeMsg_Line;
extern PACKAGE AnsiString TeeMsg_Cube;
extern PACKAGE AnsiString TeeMsg_DiagCross;
extern PACKAGE AnsiString TeeMsg_CanNotFindTempPath;
extern PACKAGE AnsiString TeeMsg_CanNotCreateTempChart;
extern PACKAGE AnsiString TeeMsg_CanNotEmailChart;
extern PACKAGE AnsiString TeeMsg_SeriesDelete;
extern PACKAGE AnsiString TeeMsg_NoSeriesSelected;
extern PACKAGE AnsiString TeeMsg_CannotLoadChartFromURL;
extern PACKAGE AnsiString TeeMsg_CannotLoadSeriesDataFromURL;
extern PACKAGE AnsiString TeeMsg_AsJPEG;
extern PACKAGE AnsiString TeeMsg_JPEGFilter;
extern PACKAGE AnsiString TeeMsg_AsGIF;
extern PACKAGE AnsiString TeeMsg_GIFFilter;
extern PACKAGE AnsiString TeeMsg_AsPNG;
extern PACKAGE AnsiString TeeMsg_PNGFilter;
extern PACKAGE AnsiString TeeMsg_AsPCX;
extern PACKAGE AnsiString TeeMsg_PCXFilter;
extern PACKAGE AnsiString TeeMsg_AsVML;
extern PACKAGE AnsiString TeeMsg_VMLFilter;
extern PACKAGE AnsiString TeeMsg_AskLanguage;
extern PACKAGE AnsiString TeeMsg_TextFile;
extern PACKAGE AnsiString TeeMsg_Gradient;
extern PACKAGE AnsiString TeeMsg_WantToSave;
extern PACKAGE AnsiString TeeMsg_NativeFilter;
extern PACKAGE AnsiString TeeMsg_Property;
extern PACKAGE AnsiString TeeMsg_Value;
extern PACKAGE AnsiString TeeMsg_Yes;
extern PACKAGE AnsiString TeeMsg_No;
extern PACKAGE AnsiString TeeMsg_Image;
extern PACKAGE AnsiString TeeMsg_FunctionCustom;
extern PACKAGE AnsiString TeeMsg_AsPDF;
extern PACKAGE AnsiString TeeMsg_PDFFilter;
extern PACKAGE AnsiString TeeMsg_AsPS;
extern PACKAGE AnsiString TeeMsg_PSFilter;
extern PACKAGE AnsiString TeeMsg_GalleryHorizArea;
extern PACKAGE AnsiString TeeMsg_SelfStack;
extern PACKAGE AnsiString TeeMsg_DarkPen;
extern PACKAGE AnsiString TeeMsg_SelectFolder;
extern PACKAGE AnsiString TeeMsg_BDEAlias;
extern PACKAGE AnsiString TeeMsg_ADOConnection;
extern PACKAGE AnsiString TeeMsg_Apply;
extern PACKAGE AnsiString TeeMsg_AddNewGroup;
extern PACKAGE AnsiString TeeMsg_ChangeGroupName;
extern PACKAGE AnsiString TeeMsg_GroupName;
extern PACKAGE AnsiString TeeMsg_FunctionMedian;
extern PACKAGE AnsiString TeeMsg_FunctionMode;
extern PACKAGE AnsiString TeeMsg_Options;
extern PACKAGE AnsiString TeeMsg_DepthTopAxis;
extern PACKAGE AnsiString TeeMsg_View2D;
extern PACKAGE AnsiString TeeMsg_Outline;
extern PACKAGE AnsiString TeeMsg_TextFilter1;
extern PACKAGE AnsiString TeeMsg_TextFilter2;
extern PACKAGE AnsiString TeeMsg_TextFilter3;
extern PACKAGE AnsiString TeeMsg_TextFilter4;
extern PACKAGE AnsiString TeeMsg_TextFilter5;
extern PACKAGE AnsiString TeeMsg_XMLFilter;
extern PACKAGE AnsiString TeeMsg_HTMLFilter;
extern PACKAGE AnsiString TeeMsg_ExcelFilter;
extern PACKAGE AnsiString TeeMsg_ViewOrthoRight;
extern PACKAGE AnsiString TeeMsg_ViewOrthoLeft;
extern PACKAGE AnsiString TeeMsg_View3DFront;
extern PACKAGE AnsiString TeeMsg_View3DRight;
extern PACKAGE AnsiString TeeMsg_View3DLeft;
extern PACKAGE AnsiString TeeMsg_AsSVG;
extern PACKAGE AnsiString TeeMsg_SVGFilter;
extern PACKAGE AnsiString TeeMsg_SubTitle;
extern PACKAGE AnsiString TeeMsg_SubFoot;
extern PACKAGE AnsiString TeeMsg_FunctionSubset;
extern PACKAGE AnsiString TeeMsg_Hexagon;
extern PACKAGE AnsiString TeeMsg_AntiAlias;
extern PACKAGE AnsiString TeeMsg_Percent;
extern PACKAGE AnsiString TeeMsg_Smooth;
extern PACKAGE AnsiString TeeMsg_Blur;
extern PACKAGE AnsiString TeeMsg_Width;
extern PACKAGE AnsiString TeeMsg_Resize;
extern PACKAGE AnsiString TeeMsg_Left;
extern PACKAGE AnsiString TeeMsg_Top;
extern PACKAGE AnsiString TeeMsg_Crop;
extern PACKAGE AnsiString TeeMsg_Invert;
extern PACKAGE AnsiString TeeMsg_GrayScale;
extern PACKAGE AnsiString TeeMsg_Mosaic;
extern PACKAGE AnsiString TeeMsg_Flip;
extern PACKAGE AnsiString TeeMsg_Reverse;
extern PACKAGE AnsiString TeeMsg_Brightness;
extern PACKAGE AnsiString TeeMsg_Color;
extern PACKAGE AnsiString TeeMsg_HueLumSat;
extern PACKAGE AnsiString TeeMsg_Sharpen;
extern PACKAGE AnsiString TeeMsg_GammaCorrection;
extern PACKAGE AnsiString TeeMsg_Emboss;
extern PACKAGE AnsiString TeeMsg_Contrast;
extern PACKAGE AnsiString TeeMsg_Rotate;
extern PACKAGE AnsiString TeeMsg_Back;
extern PACKAGE AnsiString TeeMsg_Autosize;
extern PACKAGE AnsiString TeeMsg_Mirror;
extern PACKAGE AnsiString TeeMsg_Columns;
extern PACKAGE AnsiString TeeMsg_Rows;
extern PACKAGE AnsiString TeeMsg_Tile;
extern PACKAGE AnsiString TeeMsg_Bevel;
extern PACKAGE AnsiString TeeMsg_Zoom;
extern PACKAGE AnsiString TeeMsg_ThemeDefault;
extern PACKAGE AnsiString TeeMsg_ThemeTeeChart;
extern PACKAGE AnsiString TeeMsg_ThemeExcel;
extern PACKAGE AnsiString TeeMsg_ThemeVictorian;
extern PACKAGE AnsiString TeeMsg_ThemePastels;
extern PACKAGE AnsiString TeeMsg_ThemeSolid;
extern PACKAGE AnsiString TeeMsg_ThemeClassic;
extern PACKAGE AnsiString TeeMsg_ThemeWeb;
extern PACKAGE AnsiString TeeMsg_ThemeModern;
extern PACKAGE AnsiString TeeMsg_ThemeRainbow;
extern PACKAGE AnsiString TeeMsg_ThemeWinXP;
extern PACKAGE AnsiString TeeMsg_ThemeMacOS;
extern PACKAGE AnsiString TeeMsg_ThemeWinVista;
extern PACKAGE AnsiString TeeMsg_ThemeGrayScale;
extern PACKAGE AnsiString TeeMsg_ThemeOpera;
extern PACKAGE AnsiString TeeMsg_ThemeWarm;
extern PACKAGE AnsiString TeeMsg_ThemeCool;
extern PACKAGE AnsiString TeeMsg_MenuFilters;
extern PACKAGE AnsiString TeeMsg_CrossTab;
extern PACKAGE AnsiString TeeMsg_DBSumEditCaption;
extern PACKAGE AnsiString TeeMsg_AsFlex;
extern PACKAGE AnsiString TeeMsg_FlexFilter;
extern PACKAGE AnsiString TeeMsg_AsXAML;
extern PACKAGE AnsiString TeeMsg_XAMLFilter;
extern PACKAGE AnsiString TeeMsg_SelectTmpFolder;
extern PACKAGE AnsiString TeeMsg_PathAdobeFlexCompiler;
extern PACKAGE AnsiString TeePolarDegreeSymbol;
extern PACKAGE AnsiString TeeMsg_NewChart;
extern PACKAGE AnsiString TeeMsg_RenameChart;
extern PACKAGE AnsiString TeeMsg_ChartName;
extern PACKAGE AnsiString TeeMsg_SelectTextFile;
extern PACKAGE AnsiString TeeMsg_SaveTextFile;
extern PACKAGE AnsiString TeeMsg_RecordVideo;
extern PACKAGE Classes::TStringList* TeeEnglishLanguage;
extern PACKAGE Classes::TStringList* TeeLanguage;
extern PACKAGE bool TeeLanguageHotKeyAtEnd;
extern PACKAGE bool TeeLanguageCanUpper;
extern PACKAGE void __fastcall TeeSetConstants(void);

}	/* namespace Teeconst */
using namespace Teeconst;
#pragma option pop	// -w-
#pragma option pop	// -Vx

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// TeeConst
